name: Release
on:
  push:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  release:
    permissions:
      contents: write # for release publishing

    name: Release
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    steps:
      - name: Release with semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
