name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest

    name: Testing with Bun

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: cd node_modules/@taskforcesh/message-broker && bun run postinstall
      - run: bun test
