name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test-redis:
    runs-on: ubuntu-latest

    name: Testing with Bun, redis@${{ matrix.redis-version }}

    strategy:
      matrix:
        redis-version: [7-alpine, 6-alpine]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # v3
      - uses: oven-sh/setup-bun@v1
      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - run: bun install
      - run: bun run tsc
      - run: bun test

  test-dragonflydb:
    runs-on: ubuntu-latest

    name: Testing with Bun, dragonflydb@latest

    services:
      dragonflydb:
        image: docker.dragonflydb.io/dragonflydb/dragonfly
        env:
          DFLY_cluster_mode: emulated
          DFLY_lock_on_hashtags: true
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run tsc
      - run: QUEUE_PREFIX={b} bun test
